name: Publish to NPM

on:
  push:
    branches:
      - npm
  pull_request:
    branches:
      - npm

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.2
          registry-url: https://registry.npmjs.org/

      - name: set name author
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"

      - name: patch version
        run: npm version patch --git-tag-version

      - name: publish package to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: pushing
        run: git push --follow-tags

